CREATE DATABASE agridata;
use agridata;
SELECT
    YEAR,
    STATE_NAME,
    SUM(RICE_PRODUCTION_1000_TONS) AS TOTAL_RICE_PRODUCTION
FROM agriculture
GROUP BY YEAR, STATE_NAME
ORDER BY TOTAL_RICE_PRODUCTION DESC
LIMIT 3;

SELECT
    DIST_NAME,
    MAX(WHEAT_YIELD_KG_PER_HA) - MIN(WHEAT_YIELD_KG_PER_HA) AS YIELD_INCREASE
FROM agriculture
WHERE YEAR >= (SELECT MAX(YEAR) - 5 FROM agriculture)
GROUP BY DIST_NAME
ORDER BY YIELD_INCREASE DESC
LIMIT 5;

SELECT
    STATE_NAME,
    MAX(OILSEEDS_PRODUCTION_1000_TONS) - MIN(OILSEEDS_PRODUCTION_1000_TONS) AS GROWTH
FROM agriculture
GROUP BY STATE_NAME
ORDER BY GROWTH DESC
LIMIT 5;

SELECT
    STATE_NAME,
    AVG(RICE_AREA_1000_HA) AS AVG_RICE_AREA,
    AVG(RICE_PRODUCTION_1000_TONS) AS AVG_RICE_PRODUCTION,
    AVG(WHEAT_AREA_1000_HA) AS AVG_WHEAT_AREA,
    AVG(WHEAT_PRODUCTION_1000_TONS) AS AVG_WHEAT_PRODUCTION,
    AVG(MAIZE_AREA_1000_HA) AS AVG_MAIZE_AREA,
    AVG(MAIZE_PRODUCTION_1000_TONS) AS AVG_MAIZE_PRODUCTION
FROM agriculture
GROUP BY STATE_NAME;

SELECT
    YEAR,
    STATE_NAME,
    SUM(COTTON_PRODUCTION_1000_TONS) AS TOTAL_COTTON
FROM agriculture
GROUP BY YEAR, STATE_NAME
ORDER BY TOTAL_COTTON DESC;

SELECT
    DIST_NAME,
    GROUNDNUT_PRODUCTION_1000_TONS
FROM agriculture
WHERE YEAR = 2017
ORDER BY GROUNDNUT_PRODUCTION_1000_TONS DESC
LIMIT 10;

SELECT
    YEAR,
    AVG(MAIZE_YIELD_KG_PER_HA) AS AVG_MAIZE_YIELD
FROM agriculture
GROUP BY YEAR
ORDER BY YEAR;

SELECT
    STATE_NAME,
    SUM(OILSEEDS_AREA_1000_HA) AS TOTAL_OILSEED_AREA
FROM agriculture
GROUP BY STATE_NAME
ORDER BY TOTAL_OILSEED_AREA DESC;

SELECT
    DIST_NAME,
    MAX(RICE_YIELD_KG_PER_HA) AS MAX_RICE_YIELD
FROM agriculture
GROUP BY DIST_NAME
ORDER BY MAX_RICE_YIELD DESC
LIMIT 10;

SELECT
    YEAR,
    STATE_NAME,
    SUM(RICE_PRODUCTION_1000_TONS) AS TOTAL_RICE,
    SUM(WHEAT_PRODUCTION_1000_TONS) AS TOTAL_WHEAT
FROM agriculture
GROUP BY YEAR, STATE_NAME
ORDER BY YEAR;